<?php 
    $title="Nuevo Cliente";
    $this->headTitle($title);
    $form->setAttribute('action',$this->url('user',['action'=>'add']));

    $form->prepare();

  
?>
   <h1><?php echo $this->escapeHtml($title)?></h1>

<?php 
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formHidden($form->get('phone'));
 echo $this->formHidden($form->get('type_phone'));
 echo $this->formHidden($form->get('name_user'));
 echo $this->formHidden($form->get('password'));
?>

<table>

<tr >  <td width="202px">N0 Documento:</td>
<td>
<?php 
 echo $this->formRow($form->get('dni'));

 
?>
</td>
</tr>

<tr >  <td width="202px">Nombre Completos:</td>
<td>


<?php 
 echo $this->formRow($form->get('name'));

 
?>
</td>
</tr>


<tr >  <td width="202px">Genero:</td>
<td>

<?php 
 echo $this->formRow($form->get('gender'));

 
?>

</td>
</tr>

<tr >  <td width="202px">Edad:</td>
<td>

<?php 
 echo $this->formRow($form->get('age'));

 
?>
</td>
</tr>

</table>
</br>
<?php 
 echo $this->formRow($form->get('submit'));
 

?>
