<?php 
    $title="Nuevo telefono";
    $this->headTitle($title);
    $form->setAttribute('action',$this->url('user',['action'=>'addphone','id'=>$id]) );

    $form->prepare();

  
?>
   <h1><?php echo $this->escapeHtml($title)?></h1>

<?php 
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
?>

<table>




<tr >  <td width="202px">Tipo Contacto:</td>
<td>

<?php 
 echo $this->formRow($form->get('type_phone'));

 
?>

</td>
</tr>

<tr >  <td width="202px">Telefono:</td>
<td>

<?php 
 echo $this->formRow($form->get('phone'));

 
?>
</td>
</tr>

</table>
</br>
<?php 
 echo $this->formRow($form->get('submit'));
 
 
?>
