<?php 
    $title="Editar Cliente";
    $this->headTitle($title);
    $form->setAttribute('action',$this->url('user',['action'=>'add']));
    $form->prepare();
?>
   <h1><?php echo $this->escapeHtml($title)?></h1>

<?php 
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
?>


<table>

<tr >  <td width="202px">N0 Documento:</td>
<td>
<?php 
 echo $this->formRow($form->get('dni'));

 
?>
</td>
</tr>

<tr >  <td width="202px">Nombre Completos:</td>
<td>


<?php 
 echo $this->formRow($form->get('name'));

 
?>
</td>
</tr>


<tr >  <td width="202px">Genero:</td>
<td>

<?php 
 echo $this->formRow($form->get('gender'));

 
?>

</td>
</tr>

<tr >  <td width="202px">Edad:</td>
<td>

<?php 
 echo $this->formRow($form->get('age'));

 
?>
</td>
</tr>

</table>
</br>
<?php 
 echo $this->formRow($form->get('submit'));
 $formC =new \User\Form\UserForm;
 $formC->setAttribute('action',$this->url('user',['action'=>'list']));
 $formC->prepare();

 echo $this->formRow($formC->get('back'));
 
 